### ISSUE TITLE
Request to /science not sent

### ISSUE THREAD

**Issue by TheOnlyWayUp** [0x44F/stego-discord#2]
Using Discord for Desktop
```
Stable 144604 (1d8cb60)
Host 1.0.9006
Windows 10 64-Bit (10.0.22000)
```
I'm using Discord for Web to send a message to another account which is logged in on the app.
- No code execution on client
- Request to /science not sent

Using 628248a54803739a078fb1050dbf21f0597e6780

**Comment by 0x44F** [comment]
I have tried this on canary and on lightcord / BD, works fine. Not sure about stable.

**Comment by legitloganpauler** [comment]
Same here, I think its patched or broken
